require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false
